version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: harisnvr/kittygram_backend
    env_file: .env
    volumes:
      - media:/app/media
      - static:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    image: harisnvr/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: harisnvr/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/app/media
    depends_on:
      - backend
